// AUTOGENERATED -- managed by scripts/embed-mupdf-wasm.ts. Do not edit or commit.
import { readFileSync } from "node:fs";
import wasmPath from "./mupdf-wasm.wasm" with { type: "file" };

export function loadEmbeddedMupdfWasm(): Uint8Array | undefined {
	return readFileSync(wasmPath);
}
